#!/bin/sh
#
# @name Gazebo X500 Vertical Offset -60 mm
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=v500_dual_60_N}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 11 ## Thrust Vectoring Vehicle
param set-default CA_ROTOR_COUNT 6

param set-default CA_INDEX 4  	  ## Index for the first tilting rotors
param set RC_SIM 0 		  # 0:Simulation, 1:RC, 2:Offboard
param set-default VECT_ATT_MODE 1

#### Inertia Values ####
param set-default MC_IXX 0.0147
param set-default MC_IYY 0.0182
param set-default MC_IZZ 0.0286
#### Inertia Values END ####


param set-default CA_ROTOR0_PX 0.177
param set-default CA_ROTOR0_PY 0.177
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.177
param set-default CA_ROTOR1_PY -0.177
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 	0.177
param set-default CA_ROTOR2_PY -0.177
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.177
param set-default CA_ROTOR3_PY 	0.177
param set-default CA_ROTOR3_KM -0.05


# Back fan, pushes front ####
param set-default CA_ROTOR4_PX -0.100
param set-default CA_ROTOR4_PY 0.00
# param set-default CA_ROTOR4_PZ 0.060
param set-default CA_ROTOR4_KM 0.00
param set-default CA_ROTOR4_AX -1.0
param set-default CA_ROTOR4_AY 0.0
param set-default CA_ROTOR4_AZ 0.0
#### Back fan, pushes front END ####

#### Front fan, pushes back ####
param set-default CA_ROTOR5_PX 0.100
param set-default CA_ROTOR5_PY 0.00
# param set-default CA_ROTOR5_PZ 0.060
param set-default CA_ROTOR5_KM 0.00
param set-default CA_ROTOR5_AX 1.0
param set-default CA_ROTOR5_AY 0.0
param set-default CA_ROTOR5_AZ 0.0
#### Front fan, pushes back END ####


param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106


param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150


param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default MPC_THR_HOVER 0.60
