#!/bin/sh
#
# @name Gazebo X500 Vertical Offset 80 mm
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=v500_dual_100}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 11 ## Thrust Vectoring Vehicle
param set-default CA_ROTOR_COUNT 6

param set-default CA_INDEX 4  	  ## Index for the first tilting rotors
param set RC_SIM 0 		  # 0:Simulation, 1:RC, 2:Offboard
param set-default VECT_ATT_MODE 1

#### Inertia Values ####
param set-default MC_IXX 0.0169
param set-default MC_IYY 0.0205
param set-default MC_IZZ 0.0286
#### Inertia Values END ####


param set-default CA_ROTOR0_PX 0.177
param set-default CA_ROTOR0_PY 0.177
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.177
param set-default CA_ROTOR1_PY -0.177
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 	0.177
param set-default CA_ROTOR2_PY -0.177
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.177
param set-default CA_ROTOR3_PY 	0.177
param set-default CA_ROTOR3_KM -0.05


# Back fan, pushes front ####
param set-default CA_ROTOR4_PX -0.100
param set-default CA_ROTOR4_PY 0.00
# param set-default CA_ROTOR4_PZ -0.100
param set-default CA_ROTOR4_PZ 0.00
param set-default CA_ROTOR4_KM 0.00
param set-default CA_ROTOR4_AX -1.0
param set-default CA_ROTOR4_AY 0.0
param set-default CA_ROTOR4_AZ 0.0
#### Back fan, pushes front END ####

#### Front fan, pushes back ####
param set-default CA_ROTOR5_PX 0.100
param set-default CA_ROTOR5_PY 0.00
# param set-default CA_ROTOR5_PZ -0.100
param set-default CA_ROTOR5_PZ 0.00
param set-default CA_ROTOR5_KM 0.00
param set-default CA_ROTOR5_AX 1.0
param set-default CA_ROTOR5_AY 0.0
param set-default CA_ROTOR5_AZ 0.0
#### Front fan, pushes back END ####


# #### Controller Gains #####
# param set-default MPC_XY_P 1.45

# param set-default MPC_XY_VEL_P_ACC 3.0
# param set-default MPC_XY_VEL_I_ACC 0.2
# param set-default MPC_XY_VEL_D_ACC 0.4

# param set-default MPC_PXY_P 1.40
# param set-default MPC_PXY_VEL_P_A 1.80
# param set-default MPC_PXY_VEL_I_A 0.40
# param set-default MPC_PXY_VEL_D_A 0.20

# param set-default MC_PITCHRATE_P 0.079
# param set-default MC_PITCHRATE_I 0.106
# param set-default MC_PITCHRATE_D 0.030

# param set-default MC_ROLLRATE_P 0.068
# param set-default MC_ROLLRATE_I	0.091
# param set-default MC_ROLLRATE_D	0.0013

# param set-default MC_YAWRATE_P 	0.17
# param set-default MC_YAWRATE_I	0.17
# param set-default MC_YAWRATE_D	0.00

# param set-default MC_ROLL_P  8.00
# param set-default MC_PITCH_P 7.50
# param set-default MC_YAW_P   5.54
# #### Controller Gains #####




param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106


param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150


param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default MPC_THR_HOVER 0.60
